package config

const (
	EnvServerUrl              string = "SERVER_URL"
	EnvServerReadTimeout      string = "SERVER_READ_TIMEOUT"
	EnvBaseCurrency           string = "BASE_CURRENCY"
	EnvQuoteCurrency          string = "QUOTED_CURRENCY"
	EnvStorageFilePath        string = "STORAGE_FILE_PATH"
	EnvGmailTokenPath         string = "GMAIL_TOKEN_PATH"
	EnvGmailCredentialsPath   string = "GMAIL_CREDENTIALS_PATH"
	EnvBannerApiToken         string = "BANNER_API_TOKEN"
	EnvBannerApiUrl           string = "BANNER_API_URL"
	EnvCryptoBannerTemplate   string = "CRYPTO_TEMPLATE"
	EnvCryptoHtmlMessagePath  string = "CRYPTO_MESSAGE_HTML"
	EnvCoinbaseApiExchangeUrl string = "COINBASE_API_EXCHANGE_URL"
	EnvCoinbaseApiCandlesUrl  string = "COINBASE_API_CANDLES_URL"
	EnvCoinAPIKey             string = "COINAPI_API_KEY"
	EnvNomicsApiKey           string = "NOMICS_API_KEY"
	CryptoCacheKey            string = "CRYPTO_CACHE_KEY"
	EnvDefaultExchangerName   string = "DEFAULT_EXCHANGER_NAME"
	CryptoCacheHost           string = "CRYPTO_CACHE_HOST"
	CryptoCacheDB             string = "CRYPTO_CACHE_DB"
	CryptoCacheExpiresMins    string = "CRYPTO_CACHE_EXPIRES_MINS"
	EnvLogPath                string = "DEFAULT_LOG_FILE_PATH"
)
